### ISSUE TITLE
migrations:diff error

### ISSUE THREAD

**Issue by y4roc** [lapaygroup/doctrine-cockroachdb#1]
If I want to create an diff I get an error.

`The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue.`

But when I run the sync-metadata-storage command, the result is successfully of it. So it have to be an error with the connection to cockroachdb. I hope you can help me to fix it.

**Comment by iamwildtuna** [comment]
Hello!

Show me the problematic entity, please. Are you sure you are using the latest version of the library?

Is the database empty or already with data?

If you don't want to show the entity here, you can send me to nl@wildtuna.pro

**Comment by y4roc** [comment]
Oh, there was an error in the database. After I drop the database I can create the migration.
