### ISSUE TITLE
Migration diff not running

### ISSUE THREAD

**Issue by y4roc** [lapaygroup/doctrine-cockroachdb#4]
Hello again,

I updated my entities and want to rerun `doctrine:migration:diff` to update my database. But I'm getting this error again `The metadata storage is not up to date, please run the sync-metadata-storage command to fix this issue.`

I think doctrine can't sync the database correctly from cockroachDB to entity-mapping.

**Comment by iamwildtuna** [comment]
Hello!

This problem is associated with data types. To solve it, I replaced int4. Show create table query and your entity code, please. Also tell me what version of cockroachdb do you have?

You can send it to nl@wildtuna.pro if you cannot post the code here.

**Comment by y4roc** [comment]
After I updated the platform-class from `int` to `int4` I got this error message.

```
SQLSTATE[0A000]: Feature not supported: 7 ERROR:  ALTER COLUMN TYPE from int to int4 is only supported experimentally   
  HINT:  See: https://go.crdb.dev/issue-v/49329/v21.1                                                                     
  --                                                                                                                      
  you can enable alter column type general support by running `SET enable_experimental_alter_column_type_general = true` 
  ```
  
Also I add this line `$pdo->exec('SET enable_experimental_alter_column_type_general = true');` to the driver-class at line 45.

Now I can run `doctrine:migrations:sync-metadata-storage` and `doctrine:migration:diff`. But when I want to migrate the new migration I get this errors: 

```
In AbstractPostgreSQLDriver.php line 102:
                                                                                                                                                    
  An exception occurred while executing 'ALTER TABLE cm_media_item ALTER "position" TYPE INT4':                                                     
                                                                                                                                                    
  SQLSTATE[0A000]: Feature not supported: 7 ERROR:  unimplemented: ALTER COLUMN TYPE for a column that has a constraint is currently not supported  
  HINT:  You have attempted to use a feature that is not yet implemented.                                                                           
  See: https://go.crdb.dev/issue-v/48288/v21.1
```

**Comment by iamwildtuna** [comment]
I didn't say you have a problem with int4. This was an example of a similar problem. I ask you to show the create table sql code (SHOW CREATE TABLE table_name) and the entity source code in order to understand with what other type of problem.

**Comment by iamwildtuna** [comment]
Here is the mapping types https://github.com/lapaygroup/doctrine-cockroachdb/blob/main/src/Platforms/CockroachPlatform.php#L46, which I mentioned above. Confused int4 with int8.

**Comment by y4roc** [comment]
I fixed it! I'll open a pull request soon, so it will be in this repository too.

I generated the database first with 'INT' and than a migration with 'INT4'. I'm using CockrachDB 21.1.6.
